name: kaist_map
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#CADDFF"
  adaptive_icon_foreground: "assets/images/icon-no-background.png"

dependencies:
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.5
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  webview_flutter: ^4.10.0
  http: ^1.2.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
